### PR TITLE
Reduce bookmark rewind

### PR DESCRIPTION
**Pull request by rhardin**
RE: https://github.com/singer-io/tap-exacttarget/pull/21

Made bookmark rewind configuration driven.

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @rhardin, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @rhardin!

Thank you for signing the Singer Contribution License Agreement.

**Comment by rhardin** [comment]
Anyone watching this repo?

**Comment by rhardin** [comment]
Is anyone going to look at this?

**Comment by rhardin** [comment]
@cmcarthur Hey Connor, are you still watching this repo? Mind merging this?

**Comment by rhardin** [comment]
I take it no one is watching this. We'll look for an alternative platform.

**Pull request closed without merging**
