### PR TITLE
Preliminary OAuth2 support.

### PR DESCRIPTION
**Pull request by jmtorres**
This does not handle maintaining legacy authentication, but it does appear to connect correctly with OAuth2. I'm not familiar enough to test if discovery and sync is all working correctly.

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @jmtorres, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @jmtorres!

Thank you for signing the Singer Contribution License Agreement.

**Comment by denniskopitz** [comment]
We also need this update to connect Stitch to our MC data.  Any chance of getting this update merged?

**Comment by nick-mccoy** [comment]
Hi @jmtorres  -- thanks for this submission! I work for Stitch Data, and am of the maintainers of the singer-io org. We ultimately ended up going with a different approach for enabling OAuth2 that uses a refresh_token input in this PR: #43

At the moment, we've only been able to test our changes using our Salesforce Marketing Cloud Web App to auth the same account. We'd like to ensure our Web App can auth a different account, and so we're wondering if you would work with us to test our changes. This would involve our team authorizing a test integration using credentials for your instance that you'll share with our team temporarily, so that we can make sure it's effective for production Salesforce Marketing Cloud accounts.

If you're willing to help us, please shoot us an email at stitchintegrationdev@talend.com. Thanks!

**Comment by nick-mccoy** [comment]
Closing this in favor of #47

**Pull request closed without merging**
